[2024-05-06 01:48:18,892][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=100, round_timeout=None)
[2024-05-06 01:48:21,235][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:172.17.34.49': 1.0, 'GPU': 4.0, 'accelerator_type:G': 1.0, 'CPU': 20.0, 'object_store_memory': 19066422067.0, 'memory': 38132844135.0, 'node:__internal_head__': 1.0}
[2024-05-06 01:48:21,236][flwr][INFO] - Initializing global parameters
[2024-05-06 01:48:21,236][flwr][INFO] - Requesting initial parameters from one random client
[2024-05-06 01:48:23,537][flwr][INFO] - Received initial parameters from one random client
[2024-05-06 01:48:23,537][flwr][INFO] - Evaluating initial parameters
[2024-05-06 01:48:27,063][flwr][INFO] - initial parameters (loss, other metrics): 191.90602850914001, {'accuracy': 0.1302}
[2024-05-06 01:48:27,063][flwr][INFO] - FL starting
[2024-05-06 01:48:27,064][flwr][DEBUG] - fit_round 1: strategy sampled 1 clients (out of 50)
[2024-05-06 01:48:32,535][flwr][DEBUG] - fit_round 1 received 1 results and 0 failures
[2024-05-06 01:48:33,071][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-05-06 01:48:35,070][flwr][INFO] - fit progress: (1, 435.1783666610718, {'accuracy': 0.7098}, 8.006600081920624)
[2024-05-06 01:48:35,070][flwr][DEBUG] - evaluate_round 1: strategy sampled 5 clients (out of 50)
[2024-05-06 01:48:44,480][flwr][DEBUG] - evaluate_round 1 received 5 results and 0 failures
[2024-05-06 01:48:44,480][flwr][WARNING] - No evaluate_metrics_aggregation_fn provided
[2024-05-06 01:48:44,480][flwr][DEBUG] - fit_round 2: strategy sampled 1 clients (out of 50)
[2024-05-06 01:48:49,771][flwr][DEBUG] - fit_round 2 received 1 results and 0 failures
[2024-05-06 01:48:52,292][flwr][INFO] - fit progress: (2, 638.6794328689575, {'accuracy': 0.6303}, 25.22846557945013)
[2024-05-06 01:48:52,292][flwr][DEBUG] - evaluate_round 2: strategy sampled 5 clients (out of 50)
[2024-05-06 01:49:01,488][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=4021370, ip=172.17.34.49)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
  File "/share/home/rkat6291/flwr_bnn_fromt/client.py", line 173, in evaluate
    loss, accuracy = test(self.model, self.valloader, self.device)
  File "/share/home/rkat6291/flwr_bnn_fromt/model.py", line 75, in test
    outputs = net(images)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/home/rkat6291/flwr_bnn_fromt/model.py", line 35, in forward
    x = self.fc2(x)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/home/rkat6291/flwr_bnn_fromt/models/binarized_modules.py", line 109, in forward
    weight_b=binarized(self.weight)
  File "/share/home/rkat6291/flwr_bnn_fromt/models/binarized_modules.py", line 58, in binarized
    return Binarize.apply(input,quant_mode)
  File "/share/home/rkat6291/flwr_bnn_fromt/models/binarized_modules.py", line 26, in forward
    return output.div(scale).sign().mul(scale)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 9.78 GiB total capacity; 596.18 MiB already allocated; 16.56 MiB free; 600.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2024-05-06 01:49:01,488][flwr][DEBUG] - evaluate_round 2 received 4 results and 1 failures
[2024-05-06 01:49:01,489][flwr][DEBUG] - fit_round 3: strategy sampled 1 clients (out of 50)
[2024-05-06 01:49:03,583][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=4021524, ip=172.17.34.49)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/share/home/rkat6291/flwr_bnn_fromt/client.py", line 93, in fit
    train(self.model, self.trainloader, optim, epochs, self.device)
  File "/share/home/rkat6291/flwr_bnn_fromt/model.py", line 53, in train
    net.to(device)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/rkat6291/miniconda3/envs/flower_tutorial/lib/python3.8/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[2024-05-06 01:49:03,584][flwr][DEBUG] - fit_round 3 received 0 results and 1 failures
[2024-05-06 01:49:05,576][flwr][INFO] - fit progress: (3, 638.6794328689575, {'accuracy': 0.6303}, 38.51271320134401)
[2024-05-06 01:49:05,576][flwr][DEBUG] - evaluate_round 3: strategy sampled 5 clients (out of 50)
[2024-05-06 01:49:14,854][flwr][DEBUG] - evaluate_round 3 received 5 results and 0 failures
[2024-05-06 01:49:14,855][flwr][DEBUG] - fit_round 4: strategy sampled 1 clients (out of 50)
